### ISSUE TITLE
Dynamic module navigation testing locally

### ISSUE THREAD

**Issue by nikhil-thakkar** [nikhil-thakkar/recipe-maker#2]
**Branch:** feature/onboarding

### Steps tried:
* Configure the `installApkSplitsForTest` task as per the sample from Android Github [here](https://github.com/android/app-bundle-samples).
* The above runs successfully and I see a bunch of apks pushed to emulator/device.
![image](https://user-images.githubusercontent.com/3678113/77849432-e0adae80-71cb-11ea-877f-bbc9962e9c59.png)
* Open the app from the launcher. The app doesn't navigate to the `include-dynamic` **onboarding** destination even though the module is included at `install-time`. I tried changing the delivery to `on-demand`. But still, I get the following error:
![image](https://user-images.githubusercontent.com/3678113/77849536-a1339200-71cc-11ea-9d3c-81b0cddfe2fd.png)
* The `FakeSplitInstallManager` kicks in but the module is not navigated to.

**Comment by keyboardsurfer** [comment]
This seems to be a feature naming issue as pointed out by [Wojtek on Twitter](https://twitter.com/wkalic/status/1244307735308623874).
The dynamic feature module is named `onboarding` but the module requested through `FakeSplitInstallManager` is named `onboardingFeature`.
Make the names match to resolve the issue.

**Comment by nikhil-thakkar** [comment]
Thanks @keyboardsurfer for your comment. Indeed I have acknowledged it.
Now I'm stuck on the same issue which Ian pointed out. I will keep a close watch on the [issue](https://issuetracker.google.com/issues/152131916#comment4) tracker.
Thanks again for all the collaboration :).

**Comment by nikhil-thakkar** [comment]
Closing this as not being pursued further.
